
import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import logo from "../../public/logo.svg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto px-6">
        <div className="min-h-screen flex flex-col justify-between">
          <header className="flex justify-between items-center shadow-md rounded-md mt-6 h-16 px-6 border-[1px] border-slate-100">
            <div>
              <Image width="96" height="50" src={logo} />
            </div>
            <nav>
              <ul className="flex gap-8 font-medium">
                <Link href={"/"}>Home</Link>
                <Link href={"/portfolio"}>Portfolio</Link>
                <Link href={"/blog"}>Blog</Link>
                <Link href={"/contact"}>Contact</Link>
              </ul>
            </nav>
          </header>

          {children}

          <footer className="flex flex-col text-center shadow-md rounded-tl-md rounded-tr-md border-[1px] border-slate-100 space-y-2 py-4">
            <ul className="flex justify-center gap-8">
              <li>Legal</li>
              <li>Privacy</li>
            </ul>
            <div>
              <span>Copyright &copy; 2024. All rights reserved</span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
